apiVersion: v1
kind: ConfigMap
metadata:
  name: game-users-keys
data:
  # property-like keys; each key maps to a simple value
  username: "biagio.desimone@aquasec.com"
  password: "super_secret_password"
  aws_access_key_id: "AKIAIO5FODNN7EXAMPLE"