---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunger-check-deployment2
  namespace: big-monolith
spec:
  selector:
    matchLabels:
      app: hunger-check
  template:
    metadata:
      labels:
        app: hunger-check
    spec:
      serviceAccountName: big-monolith-sa
      containers:
      - name: hunger-check
        image: madhuakula/k8s-goat-hunger-check
        ports:
        - containerPort: 8080
